version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cractro_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/cractro_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: cractro_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/src/mongo-init.js:ro

  redis:
    image: redis:alpine
    container_name: cractro_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
